In [1]:
import torch

In [ ]:
word = torch.tensor([1,2,3,4])
max(word).item()

4

In [4]:
torch.max(m)

tensor(4)

In [25]:
int_type=torch.int16
device='cpu'
words = [[1,4,5], [4,5,6,7], [6,7,8,8,8]]
m = max([len(word) for word in words])
words = [torch.cat(
        (torch.tensor(word, dtype=int_type, device=device),
        -1 * torch.ones(m - len(word), dtype=int_type, device=device)),
        dim = 0
    ) for word in words]
words = torch.cat(tuple(word.unsqueeze(0) for word in words), dim=0)
print(words)

tensor([[ 1,  4,  5, -1, -1],
        [ 4,  5,  6,  7, -1],
        [ 6,  7,  8,  8,  8]], dtype=torch.int16)


In [26]:
mask = torch.where(words == -1, False, True)
print(mask)

tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])


In [31]:
pairs = torch.stack((words[:, :-1], words[:, 1:]), dim=0)
print(pairs)

tensor([[[ 1,  4,  5, -1],
         [ 4,  5,  6,  7],
         [ 6,  7,  8,  8]],

        [[ 4,  5, -1, -1],
         [ 5,  6,  7, -1],
         [ 7,  8,  8,  8]]], dtype=torch.int16)


In [ ]:
unique, counts = torch.unique(pairs, sorted=False, return_counts=True, dim=1)
print(unique)
print(counts)

tensor([[[-1,  1,  4,  5],
         [ 7,  4,  5,  6],
         [ 8,  6,  7,  8]],

        [[-1,  4,  5, -1],
         [-1,  5,  6,  7],
         [ 8,  7,  8,  8]]], dtype=torch.int16)
tensor([1, 1, 1, 1])
